
```{r setup, include=FALSE}
#install.packages("knitr")
#install.packages("dplyr")
#install.packages("ggplot2")

library(dplyr)
library(ggplot2)

knitr::opts_chunk$set(echo = TRUE)
```

# Importanto os dados

```{r warning=FALSE, message=FALSE, error=FALSE}
get_timestamp_diff <- function(df){
  
  begin = df %>% filter(df$MOMENTO == "BEGIN")
  end = df %>% filter(df$MOMENTO == "END")
  
  df = left_join(begin, end, by=c("ID", "TIPO_REQUISICAO"))
  df$TIMESTAMP = ((df$TIMESTAMP.y) - (df$TIMESTAMP.x) ) / 1000000
  df = df %>% select("ID", "TIPO_REQUISICAO", "TIMESTAMP")

  return(df)
}
```

```{r warning=FALSE, message=FALSE, error=FALSE}
requests.all <- data.frame() 
experimentos = c(1:40)

for (e in experimentos) {
  
  path_500mb = paste("../data/500MB/", "E", e, sep="")
  path_1gb = paste("../data/1GB/", "E", e, sep="")
  
  get.80.1g = read.csv2(file=paste(path_1gb, "/request_get_80_consumptions.csv", sep=""), sep = ",")
  get.180.1g = read.csv2(file=paste(path_1gb, "/request_get_180_consumptions.csv", sep=""), sep=",")
  post.80.1g = read.csv2(file=paste(path_1gb, "/request_post_80_create_water_consumption.csv", sep=""), sep=",")
  post.180.1g = read.csv2(file=paste(path_1gb, "/request_post_180_create_water_consumption.csv", sep=""), sep=",")
  
  get.80.500m = read.csv2(file=paste(path_500mb, "/request_get_80_consumptions.csv", sep=""), sep = ",")
  get.180.500m = read.csv2(file=paste(path_500mb, "/request_get_180_consumptions.csv", sep=""), sep=",")
  post.80.500m = read.csv2(file=paste(path_500mb, "/request_post_80_create_water_consumption.csv", sep=""), sep=",")
  post.180.500m = read.csv2(file=paste(path_500mb, "/request_post_180_create_water_consumption.csv", sep=""), sep=",")
  
  get.180.1g = get_timestamp_diff(get.180.1g)
  get.180.500m = get_timestamp_diff(get.180.500m)
  get.80.1g = get_timestamp_diff(get.80.1g)
  get.80.500m = get_timestamp_diff(get.80.500m)
  post.180.1g = get_timestamp_diff(post.180.1g)
  post.180.500m = get_timestamp_diff(post.180.500m)
  post.80.1g = get_timestamp_diff(post.80.1g)
  post.80.500m = get_timestamp_diff(post.80.500m)

  get.180.1g["RAM"] <- 1024
  get.180.500m["RAM"] <- 500

  get.180.1g["REQ_MIN"] <- 180
  get.180.500m["REQ_MIN"] <- 180

  post.180.1g["RAM"] <- 1024
  post.180.500m["RAM"] <- 500

  post.180.1g["REQ_MIN"] <- 180
  post.180.500m["REQ_MIN"] <- 180

  get.80.1g["RAM"] <- 1024
  get.80.500m["RAM"] <- 500

  get.80.1g["REQ_MIN"] <- 80
  get.80.500m["REQ_MIN"] <- 80

  post.80.1g["RAM"] <- 1024
  post.80.500m["RAM"] <- 500

  post.80.1g["REQ_MIN"] <- 80
  post.80.500m["REQ_MIN"] <- 80

  post.all <- rbind(post.180.1g,post.180.500m,post.80.1g,post.80.500m)
  get.all <- rbind(get.180.1g,get.180.500m,get.80.1g,get.80.500m)
  
  post.all["EXPERIMENTO"] <- e
  get.all["EXPERIMENTO"] <- e
  
  requests.all <- rbind(requests.all, post.all, get.all)
}
```

```{r}
requests.all = requests.all[complete.cases(requests.all), ]
```

# Gráficos

```{r fig.height=7}
requests.all %>%
  ggplot(aes(x=as.factor(RAM), y=TIMESTAMP, colour=as.factor(REQ_MIN))) + 
  geom_boxplot() +
  scale_y_log10() +
  facet_wrap(~ EXPERIMENTO, ncol = 10) + 
  
  ggtitle("Comportamento de tempos de respostas para requisições nos 40 ensaios") +
  xlab("Limite de memória disponível") +
  ylab("Tempo de resposta (milissegundos)") +
  theme(legend.title=element_blank()) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.ticks.x = element_blank()) +
  theme(axis.text.x = element_blank()) 
```

```{r fig.height=7}
requests.all %>%
  ggplot(aes(x=as.factor(RAM), y=TIMESTAMP, colour=as.factor(REQ_MIN))) + 
  geom_boxplot() +
  ylim(1, 100) +
  facet_wrap(~ EXPERIMENTO, ncol = 10) + 
  
  ggtitle("Comportamento de tempos de respostas para requisições nos 40 ensaios") +
  labs(subtitle = "Requisições abaixo ou igual a 100 milissegundos de reposta") +
  xlab("Limite de memória disponível") +
  ylab("Tempo de resposta (milissegundos)") +
  theme(legend.title=element_blank()) +
  theme(plot.title = element_text(hjust = 0.5)) 
```

```{r}
corr.time.memo = requests.all %>% 
  summarise(correlacao = cor(TIMESTAMP, RAM, method = "pearson"))
corr.time.memo["VAR"] = "Memória disponível"

corr.time.tipo = requests.all %>% 
  summarise(correlacao = cor(TIMESTAMP, as.numeric(TIPO_REQUISICAO), method = "pearson"))
corr.time.tipo["VAR"] = "Tipo de requisição"

corr.time.freq = requests.all %>% 
  summarise(correlacao = cor(TIMESTAMP, REQ_MIN, method = "pearson"))
corr.time.freq["VAR"] = "Requisições por minuto"

correlacoes = rbind(corr.time.freq, corr.time.memo, corr.time.tipo)

correlacoes %>%
  ggplot(aes(x = reorder(VAR, correlacao), y = correlacao, fill = VAR)) +
  geom_bar(stat = "identity", alpha = .7, width = .75) +

  labs(title = 'Correlação entre Fatores e Tempo de resposta de requisição') +  
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position="none") +
  theme(axis.title.y=element_blank()) +
  coord_flip()
```

```{r}
requests.all %>%
  ggplot(aes(x=as.factor(RAM), y=TIMESTAMP, colour=as.factor(REQ_MIN))) + 
  geom_boxplot() +
  ylim(1, 100) +
  facet_wrap(~ TIPO_REQUISICAO, ncol = 2) +
  
  ggtitle("Comparando tempos de respostas para tipos de requisições ") +
  xlab("Limite de memória disponível") +
  ylab("Tempo de resposta (milissegundos)") +
  theme_bw() +
  theme(legend.title=element_blank()) +
  theme(plot.title = element_text(hjust = 0.5)) 
```

```{r}
plot = requests.all %>%
  ggplot(aes(x=as.factor(REQ_MIN), y=TIMESTAMP, color=as.factor(TIPO_REQUISICAO))) + 
  geom_boxplot() +
  ylim(1, 100) +
  facet_wrap(~ RAM, ncol = 2) +
  
  ggtitle("Comparando tempos de respostas para limites de memórias diferentes") +
  xlab("Requisições por minuto") +
  ylab("Tempo de resposta (milissegundos)") +
  theme_bw() +
  theme(legend.title=element_blank()) +
  theme(plot.title = element_text(hjust = 0.5)) 
  #theme(axis.ticks.x = element_blank()) +
  #theme(axis.text.x = element_blank()) 
plot
ggplot_build(plot)$data
```

```{r}
requests.all$rowname <- rownames(requests.all)

requests.all %>%
  group_by(EXPERIMENTO) %>%
  summarise(mediana = median(TIMESTAMP)) %>%

  ggplot(aes(x=EXPERIMENTO, y=mediana)) +
  geom_point(color="gold4") + 
  
  ggtitle("Mediana dos tempos de resposta nos experimentos") +
  xlab("Experimentos") +
  ylab("Mediana do tempo de resposta (milissegundos)") +
  theme_bw() +
  theme(legend.title=element_blank()) +
  theme(plot.title = element_text(hjust = 0.5)) 
  
```

```{r fig.height=5, fig.width=4}
d = requests.all %>% filter(TIPO_REQUISICAO == "POST") %>% select(TIMESTAMP)
d %>%
  ggplot(aes(x=0, y=TIMESTAMP)) +
  geom_boxplot(color="deeppink3") +
  ylim(1, 100) +

  ggtitle("Boxplot") +
  labs(subtitle = "Fator=Tipo de Requisição, Nível=POST") +
  ylab("Tempo de resposta (milissegundos)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.title.x = element_blank()) +
  theme(axis.text.x = element_blank()) 

summary(d)
```

```{r fig.height=5, fig.width=4}
d = requests.all %>% filter(TIPO_REQUISICAO == "GET") %>% select(TIMESTAMP)
d %>%
  ggplot(aes(x=0, y=TIMESTAMP)) +
  geom_boxplot(color="darkblue") +
  ylim(1, 100) +

  ggtitle("Boxplot") +
  labs(subtitle = "Fator=Tipo de Requisição, Nível=GET") +
  ylab("Tempo de resposta (milissegundos)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.title.x = element_blank()) +
  theme(axis.text.x = element_blank()) 

summary(d)
```

```{r fig.height=5, fig.width=4}
d = requests.all %>% filter(RAM == 500) %>% select(TIMESTAMP)
d %>%
  ggplot(aes(x=0, y=TIMESTAMP)) +
  geom_boxplot(color="darkred") +
  ylim(1, 100) +

  ggtitle("Boxplot") +
  labs(subtitle = "Fator=RAM, Nível=500") +
  ylab("Tempo de resposta (milissegundos)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.title.x = element_blank()) +
  theme(axis.text.x = element_blank()) 

summary(d)
```

```{r fig.height=5, fig.width=4}
d = requests.all %>% filter(RAM == 1024) %>% select(TIMESTAMP)
d %>%
  ggplot(aes(x=0, y=TIMESTAMP)) +
  geom_boxplot(color="darkgreen") +
  ylim(1, 100) +

  ggtitle("Boxplot") +
  labs(subtitle = "Fator=RAM, Nível=1024") +
  ylab("Tempo de resposta (milissegundos)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.title.x = element_blank()) +
  theme(axis.text.x = element_blank()) 

summary(d)
```
